name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  token:  # id of input
    description: 'id token'
    required: true
  channel:
    description: 'channel ID'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
